"""
backtester.py — The main event loop.

This is the heart of the system. It:
  1. Pulls one bar from the data handler (MarketEvent)
  2. Drains the event queue completely before pulling the next bar

WHY DRAIN BEFORE NEXT BAR:
  A MarketEvent may produce a SignalEvent, which produces an OrderEvent,
  which produces a FillEvent — all within the same "bar". We must fully
  process this chain before advancing time. This prevents look-ahead bias
  and mirrors how a live system processes messages.

THE LOOP:
  while data:
      emit next bar → queue has [MarketEvent]
      while queue not empty:
          event = queue.get()
          dispatch to all handlers

This two-level loop is the defining architecture of an event-driven backtester.
"""

from queue import Queue, Empty

from events import EventType, MarketEvent, SignalEvent, OrderEvent, FillEvent
from data import HistoricalDataHandler
from strategy import MomentumStrategy
from portfolio import Portfolio
from execution import SimulatedExecutionHandler
from performance import compute_performance, print_report


class Backtester:

    def __init__(
        self,
        symbol:          str   = "BTCUSDT",
        interval:        str   = "4h",
        limit:           int   = 1000,
        initial_capital: float = 10_000.0,
        fast_period:     int   = 12,
        slow_period:     int   = 26,
        slippage_pct:    float = 0.0005,
        commission_pct:  float = 0.001,
        position_pct:    float = 0.95,
        max_drawdown_pct: float = 0.20,
    ):
        self.symbol   = symbol.upper()
        self.interval = interval

        # Shared event queue — all components communicate through this
        self.event_queue = Queue()

        # Shared price tracker (execution handler needs latest close)
        self.last_prices: dict = {}

        # ── Instantiate all components ──────────────────────────────────────
        self.data_handler = HistoricalDataHandler(
            event_queue = self.event_queue,
            symbol      = symbol,
            interval    = interval,
            limit       = limit,
        )

        self.portfolio = Portfolio(
            event_queue      = self.event_queue,
            initial_capital  = initial_capital,
            position_pct     = position_pct,
            max_drawdown_pct = max_drawdown_pct,
        )

        self.strategy = MomentumStrategy(
            event_queue    = self.event_queue,
            data_handler   = self.data_handler,
            symbol         = symbol,
            fast_period    = fast_period,
            slow_period    = slow_period,
        )

        self.execution = SimulatedExecutionHandler(
            event_queue    = self.event_queue,
            last_prices    = self.last_prices,
            slippage_pct   = slippage_pct,
            commission_pct = commission_pct,
        )

    def _dispatch(self, event):
        """Route an event to all relevant handlers."""
        if event.type == EventType.MARKET:
            self.last_prices[event.symbol] = event.close
            self.portfolio.on_market(event)
            self.strategy.on_market(event)

        elif event.type == EventType.SIGNAL:
            self.portfolio.on_signal(event)

        elif event.type == EventType.ORDER:
            self.execution.on_order(event)

        elif event.type == EventType.FILL:
            self.portfolio.on_fill(event)

    def run(self) -> dict:
        """
        Execute the backtest.
        Returns the performance metrics dict.
        """
        print(f"\n[Backtester] Starting: {self.symbol} | {self.interval} | "
              f"{len(self.data_handler)} bars\n")

        bar_count = 0

        while self.data_handler.has_next():
            # ── Emit next bar ────────────────────────────────────────────────
            self.data_handler.stream_next()
            bar_count += 1

            # ── Drain all events generated by this bar ───────────────────────
            while True:
                try:
                    event = self.event_queue.get(block=False)
                    self._dispatch(event)
                except Empty:
                    break   # No more events for this bar; advance to next

        print(f"\n[Backtester] Finished. Processed {bar_count} bars.")
        print(f"[Backtester] Portfolio: {self.portfolio.summary()}")

        metrics = compute_performance(
            equity_curve     = self.portfolio.equity_curve,
            trade_log        = self.portfolio.trade_log,
            interval         = self.interval,
            initial_capital  = self.portfolio.initial_capital,
        )

        print_report(metrics)
        return metrics
